groupsboard/gbweb/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path('', views.home, name="index"),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('home', views.home, name="home"),

    path('lider/<str:id>/', views.lider, name="lider"),
    path('estudiante/<str:id>/', views.estudiante, name="estudiante"),
    path('user_lider/', views.user_lider, name="user_lider"),
    path('user_estudiante/', views.user_estudiante, name="user_estudiante"),
    path('ver_estudiantes/<int:id>/', views.ver_estudiantes, name="ver_estudiantes"),
    path('account/', views.accountSettings, name='account'),


    path('create_group/', views.create_group, name="create_group"),
    path('groups/', views.group, name="groups"),
    path('group_detail/<int:id>/', views.group_detail, name="group_detail"),
    path('update_group/<str:pk>/', views.updateGroup, name="update_group"),
    path('delete_group/<str:pk>/', views.deleteGroup, name="delete_group"),
   
    path('create_task/', views.create_task, name='create_task'),
    path('tasks/', views.tasks, name='tasks'),
    path('update_task/<str:pk>/', views.updateTask, name="update_task"),
    path('delete_task/<str:pk>/', views.deleteTask, name="delete_task"),

    path('users/', views.ListarUsuarios.as_view(), name="users"),
]

groupsboard/groupsboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gbweb.urls')),
]

groupsboard/gbweb/models.py
'''
Models classes
'''
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
options_type=(
    ('Público','Público'),
    ('Privado','Privado')
    )

class Lider(models.Model):
    lider = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    legajo = models.CharField(max_length=100, verbose_name='Legajo')
   
    
    def __str__(self):
        return self.lider.username

class Estudiante(models.Model):
    estudiante = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    legajo = models.CharField(max_length=100, verbose_name='Legajo')

    def __str__(self):
        return self.estudiante.username

class Grupo(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del grupo:')
    tipo = models.CharField(max_length=10, choices=options_type)
    tema =models.CharField(max_length=200, verbose_name='Tema del grupo')
    descripcion = models.CharField(max_length=200, verbose_name='Descripción del grupo')
    proximo_encuentro = models.DateField(verbose_name='Próxima reunión')
    lider= models.ForeignKey(Lider, on_delete=models.CASCADE)
    estudiante = models.ManyToManyField(Estudiante)

    def __str__(self):
        return self.nombre
    
class Tarea(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(null=True, verbose_name='Descripción')
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    terminado = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo + ' - ' + self.grupo.nombre

groupsboard/gbweb/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import *

from django.core.exceptions import ValidationError

class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise ValidationError("Error!!! Ya hay un usuario inscripto con ese e-mail")

        return self.cleaned_data
   
class CreateGroupForm(ModelForm):
    
    class Meta:
        model = Grupo
        fields = '__all__'


class Create_Task(ModelForm):
    
    class Meta:
        model = Tarea
        fields = '__all__'
        widgets = {
            'description':Textarea(attrs={'cols':20,'rows': 10}),
        }

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        help_texts = {
            'password': (''),
        }
        fields = ['username', 'first_name', 'last_name', 'email']
        

groupsboard/gbweb/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.contrib.auth.models import Group

from django.views.generic.list import ListView
from .forms import CreateUserForm, Create_Task, CreateGroupForm, UserChangeForm
from .filters import GrupoFiltro
from .forms import CreateUserForm, Create_Task, CreateGroupForm, UserChangeForm
from .filters import GrupoFiltro

from . models import *


def index(request):
    return render(request, 'index.html')

def sign_up(request):
    create_user_form = CreateUserForm()
    if request.method == 'POST':
        create_user_form = CreateUserForm(request.POST)
        if create_user_form.is_valid():
            user = create_user_form.save()
            username = create_user_form.cleaned_data.get('username')

            messages.success(request, 'La cuenta de ' + username + ' fue creada con exito')
            return redirect('sign_in')
    
    context={'form': create_user_form}
    return render(request, 'login/sign_up.html', context)

def sign_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect')

    context={}
    return render(request, 'login/sign_in.html', context)


def logout_user(request):
    logout(request)
    return redirect('sign_in')


@login_required(login_url='sign_in')
def home(request): 
    tareas = Tarea.objects.all()
    grupos = Grupo.objects.all()
    lideres = Lider.objects.all()
    estudiantes = Estudiante.objects.all()

    grupos_totales = grupos.count()
    tareas_totales = tareas.count()

    filtro = GrupoFiltro(request.GET, queryset=grupos)
    grupos = filtro.qs

    
    context = {'tareas':tareas, 'grupos':grupos, 'lideres': lideres, 'grupos_totales':grupos_totales, 'tareas_totales': tareas_totales, 'estudiantes':estudiantes, 'filtro':filtro}
    filtro = GrupoFiltro(request.GET, queryset=grupos)
    grupos = filtro.qs

    
    context = {'tareas':tareas, 'grupos':grupos, 'lideres': lideres, 'grupos_totales':grupos_totales, 'tareas_totales': tareas_totales, 'estudiantes':estudiantes, 'filtro':filtro}

    return render(request, 'dashboard/dashboard.html', context)
    

class ListarUsuarios(ListView):
    model = User
    context_object_name = 'Usuarios'
    template_name = 'users/listar_usuarios.html'
    ordering = ['last_name']


login_required(login_url='sign_in')
def lider(request, id):
    lider = Lider.objects.get(lider_id=id)

    grupos = lider.grupo_set.all()
    grupos_count = grupos.count()

    context = {'lider':lider, 'grupos':grupos, 'grupos_count':grupos_count}
    return render(request, 'users/lider.html', context)



@login_required(login_url='sign_in')
def estudiante(request, id):
    estudiante = Estudiante.objects.get(estudiante_id=id)

    grupos = estudiante.grupo_set.all()
    grupos_count = grupos.count()

    filtro = GrupoFiltro(request.GET, queryset=grupos)
    grupos = filtro.qs
    filtro = GrupoFiltro(request.GET, queryset=grupos)
    grupos = filtro.qs

    context ={'estudiante':estudiante, 'grupos':grupos, 'grupos_count': grupos_count, 'filtro':filtro}
    context ={'estudiante':estudiante, 'grupos':grupos, 'grupos_count': grupos_count, 'filtro':filtro}
    return render(request, 'users/estudiante.html', context)

def user_lider(request):
    
    lider = request.user.lider
    grupos = request.user.lider.grupo_set.all()
    grupos_total = grupos.count()
   

    context ={'lider':lider, 'grupos':grupos, 'grupos_total':grupos_total}
    return render(request, 'users/user.html', context)

def user_estudiante(request):
    estudiantes = Estudiante.objects.get(estudiante = request.user)
    grupos = estudiantes.grupo_set.all()
    grupos_total = grupos.count()
    
    context ={'estudiantes':estudiantes, 'grupos':grupos, 'grupos_total':grupos_total}
    return render(request, 'users/user.html', context)


def ver_estudiantes(request, id ):
    grupo = Grupo.objects.get(id=id)
   
    context = {'grupo':grupo}
    return render(request, 'users/ver_estudiantes.html', context)


def accountSettings(request):
    usuario = request.user
    form =UserChangeForm(instance=usuario)

    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()
        
    
    context ={'form':form}
    return render(request, 'users/account_settings.html', context)


@login_required(login_url='sign_in')
def group(request):
    grupos = Grupo.objects.all()
    context = {'grupos': grupos}

    return render(request, 'groups/groups.html',context)


@login_required(login_url='sign_in')
def create_group(request):
    form = CreateGroupForm()

    if request.method == 'POST':
        form = CreateGroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('groups')
    
    context = {'form':form}
    return render(request, 'groups/create_group.html', context)


@login_required(login_url='sign_in')
def group_detail(request, id):
    grupos = Grupo.objects.get(id=id)
    grupos = Grupo.objects.get(id=id)
    tareas = Tarea.objects.filter(grupo_id = id)



    context = {'grupos': grupos, 'tareas': tareas}
    return render(request, 'groups/group_detail.html',context)


def updateGroup(request, pk):
    grupo = Grupo.objects.get(id=pk)
    form = CreateGroupForm(instance=grupo)

    if request.method == 'POST':
        form = CreateGroupForm(request.POST, instance=grupo)
        if form.is_valid():
            form.save()
            return redirect('home')
    
    context ={'form':form}
    return render(request, 'groups/create_group.html', context)


def deleteGroup(request, pk):
    grupo = Grupo.objects.get(id=pk)

    if request.method == "POST":
        grupo.delete()
        return redirect('home')
    
    context={'grupo':grupo}
    return render(request, 'groups/delete.html', context)

@login_required(login_url='sign_in')
def tasks(request):
    tareas = Tarea.objects.all()
    context = {'tareas' : tareas}
    return render(request, 'tasks/tasks.html', context)


@login_required(login_url='sign_in')
def create_task(request):
    grupo = Grupo.objects.all()
    form = Create_Task(initial={'grupo':grupo})

    if request.method == 'POST':
        form = Create_Task(request.POST)
        if form.is_valid():
            form.save()
            return redirect('groups')
        
    context = {'form':form}
    return render(request, 'tasks/create_task.html', context)


def updateTask(request, pk):
    tarea = Tarea.objects.get(id=pk)
    form = Create_Task(instance=tarea)

    if request.method == 'POST':
        form = Create_Task(request.POST, instance=tarea)
        if form.is_valid():
            form.save()
            return redirect('home')
    
    context ={'form':form}
    return render(request, 'tasks/create_task.html', context)


def deleteTask(request, pk):
    tarea = Tarea.objects.get(id=pk)

    if request.method == "POST":
        tarea.delete()
        return redirect('home')
    
    context={'tarea':tarea}
    return render(request, 'tasks/delete.html', context)

groupsboard/gbweb/templates/users/account_settings.html
{% extends 'layouts/base_con_login.html' %}
{% load static %}
{% block content %}

<style>
    .profile-pic{
        max-width: 200px;
        max-height: 200px;
        margin: 0 auto;
        border-radius: 50%;
    }
</style>

<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            {% if perms.gbweb.add_estudiante %}
                <a href="{% url 'user_lider' %}" class="btn btn-warning">&#8592; Back to Profile</a>
            {% else %}
                <a href="{% url 'user_estudiante' %}" class="btn btn-warning">&#8592; Back to Profile</a>
            {% endif %}
                <hr>
                <h3 style="text-align: center;">Account Settings</h3>
                <hr>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card card-body">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary" name="Update Information">
            </form>
            
        </div>
    </div>
</div>

{% endblock %}

groupsboard/gbweb/templates/users/estudiante.html
{% extends 'layouts/base_con_login.html' %}

{% block title %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Informacion de Contacto</h5>
            <hr>
            <p>Nombre: {{estudiante.estudiante.first_name}}</p>
            <p>Apellido: {{estudiante.estudiante.last_name}}</p>
            <p>Email: {{estudiante.estudiante.email}}</p>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Grupos Totales</h5>
            <hr>
            <h1 style="text-align: center; padding: 10px;">{{grupos_count}}</h1>
        </div>
    </div>

</div>

<br>

<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">
                {{filtro.form}}
            <button class="btn btn-primary" type="submit">Buscar</button>
            </form>
           
        </div>
    </div>
</div>

<br>


<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>nombre</th>
                    <th>tipo</th>
                    <th>tema</th>
                    <th>descripcion</th>
                </tr>
                {% for grupo in grupos %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'ver_estudiantes' grupo.id %}">Ver estudiantes</a></td>
                    <td>{{grupo.nombre}}</td>
                    <td>{{grupo.tipo}}</td>
                    <td>{{grupo.tema}}</td>
                    <td>{{grupo.descripcion}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

groupsboard/gbweb/templates/users/lider.html
{% extends 'layouts/base_con_login.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
           <h5>Lider</h5>
            <hr>
            <a class="btn btn-outline-info btn-sm btn-block" href="#">Actualizar Lider de grupo</a>
            <a class="btn btn-outline-info btn-sm btn-block" href="#">Crear grupo</a> 
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Informacion de Contacto</h5>
            <hr>
            <p>Nombre: {{lider.lider.first_name}}</p>
            <p>Apellido: {{lider.lider.last_name}}</p>
            <p>Email: {{lider.lider.email}}</p>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Grupos Totales</h5>
            <hr>
            <h1 style="text-align: center; padding: 10px;">{{grupos_count}}</h1>
        </div>
    </div>

</div>

<br>



<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>nombre</th>
                    <th>tipo</th>
                    <th>tema</th>
                    <th>descripcion</th>
                    {% comment %} <th>Update</th>
                    <th>Remove</th> {% endcomment %}
                </tr>
                {% for grupo in grupos %}
                <tr>
                    <td>{{grupo.nombre}}</td>
                    <td>{{grupo.tipo}}</td>
                    <td>{{grupo.tema}}</td>
                    <td>{{grupo.descripcion}}</td>
                    {% comment %} <td><a class="btn btn-sm btn-info" href="{% url 'update_order' order.id %}">Update</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'delete_order' order.id %}">Delete</a></td> {% endcomment %}
                </tr>
                
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

groupsboard/gbweb/templates/users/listar_usuarios.html
{% extends 'layouts/base_con_login.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/create_form.css' %}">
{% endblock %}

{% block title %}Listado de Usuarios{% endblock %}

{% block content %}
<h1>Groups Board</h1>
<h2>Listado de Usuarios</h2>
<section class="lista">
    {% for usuario in Usuarios %}
        <article>
            <p><b>Nombre</b>: {{usuario.username}}</p>
            <p><b>Apellido</b>: {{usuario.apellido}}</p>
            <p><b>Email</b>: {{usuario.email}}</p>
            <p><b>DNI</b>: {{usuario.dni}}</p>
            <p><b>Username</b>: {{usuario.username}}</p>
            <p><b>Password</b>: {{usuario.password}}</p>
        </article>
    {% empty %}
        <article>No hay Usuarios cargados</article>
    {% endfor %}
</section>

{% endblock %}

groupsboard/gbweb/templates/users/user.html
{% extends 'layouts/base_con_login.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Informacion de Contacto</h5>
            <hr>
            {% if perms.gbweb.add_estudiante %} 
                <p>Nombre: {{lider.lider.first_name}}</p>
                <p>Apellido: {{lider.lider.last_name}}</p>
                <p>Email: {{lider.lider.email}}</p>
            {% else %}
                <p>Nombre: {{estudiantes.estudiante.first_name}}</p>
                <p>Apellido: {{estudiantes.estudiante.last_name}}</p>
                <p>Email: {{estudiantes.estudiante.email}}</p>
            {% endif %} 
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Grupos Totales</h5>
            <hr>
            <h1 style="text-align: center; padding: 10px;">{{grupos_total}}</h1>
        </div>
    </div>

</div>

<br>



<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>nombre</th>
                    <th>tipo</th>
                    <th>tema</th>
                    <th>descripcion</th>
                </tr>
                {% for grupo in grupos %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'ver_estudiantes' grupo.id %}">Ver estudiantes</a></td>
                    <td>{{grupo.nombre}}</td>
                    <td>{{grupo.tipo}}</td>
                    <td>{{grupo.tema}}</td>
                    <td>{{grupo.descripcion}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

groupsboard/gbweb/templates/users/ver_estudiantes.html
{% extends 'layouts/base_con_login.html' %}

{% block title %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
          
<h5>{{grupo.nombre}}</h5>

{% for estudiantes in grupo.estudiante.all %}

<h5>{{estudiantes.estudiante.first_name}}</h5>

{% endfor %}




{% endblock %}